claude-multiagent-pm:
  framework_location: /Users/masa/Projects/claude-multiagent-pm
  initialized_at: '2025-07-09 12:18:03'
  is_project_specific: false
  mode: working-directory
  project_directory: /Users/masa/Projects/managed/ai-trackdown-tools
  version: 4.2.3
  working_directory: /Users/masa/Projects/managed/ai-trackdown-tools
logging:
  level: INFO
  log_dir: ./logs/working
  max_log_size: 10MB
  rotate_logs: true
session:
  auto_save: true
  session_id: working-1752077883
  session_path: ./sessions
