name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tested with the latest version of ai-trackdown-tools
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use flags '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Command Output
      description: Please paste any relevant command output or error messages
      render: shell
      placeholder: Paste command output here...

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "v18.17.0"
    validations:
      required: true

  - type: input
    id: tool-version
    attributes:
      label: ai-trackdown-tools Version
      description: What version of ai-trackdown-tools are you using?
      placeholder: "0.4.0"
    validations:
      required: true

  - type: input
    id: npm-version
    attributes:
      label: NPM Version
      description: What version of NPM are you using?
      placeholder: "9.8.1"

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment details that might be relevant
      placeholder: |
        - Terminal: iTerm2 / Windows Terminal / etc.
        - Shell: bash / zsh / fish / powershell
        - CI/CD: GitHub Actions / Jenkins / etc.

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How would you rate the severity of this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Blocks functionality, no workaround
        - Critical - Application crashes or data loss
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, logs, related issues, etc.