name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run typecheck
          npm run lint
          npm test
          npm run build

      - name: Check if PR is minor/patch update
        id: check-update-type
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const body = context.payload.pull_request.body || '';
            
            // Check for security updates
            const isSecurityUpdate = title.includes('security') || 
                                   body.includes('security') ||
                                   title.includes('vulnerability');
            
            // Check for minor/patch updates
            const isMinorUpdate = title.includes('minor') || 
                                title.includes('patch') ||
                                /bump.*from.*\d+\.\d+\.\d+.*to.*\d+\.\d+\.\d+/.test(title);
            
            // Check for major updates
            const isMajorUpdate = title.includes('major') ||
                                /bump.*from.*\d+\.\d+\.\d+.*to.*(\d+)\.\d+\.\d+/.test(title);
            
            console.log('Security update:', isSecurityUpdate);
            console.log('Minor update:', isMinorUpdate);
            console.log('Major update:', isMajorUpdate);
            
            return {
              isSecurityUpdate,
              isMinorUpdate,
              isMajorUpdate,
              shouldAutoMerge: isSecurityUpdate || (isMinorUpdate && !isMajorUpdate)
            };

      - name: Auto-approve and merge
        if: fromJSON(steps.check-update-type.outputs.result).shouldAutoMerge
        uses: actions/github-script@v7
        with:
          script: |
            const { pull_request } = context.payload;
            
            // Approve the PR
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request.number,
              event: 'APPROVE',
              body: '✅ Auto-approved by Dependabot workflow after successful tests'
            });
            
            // Enable auto-merge
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request.number,
              commit_title: `${pull_request.title} (#${pull_request.number})`,
              commit_message: 'Auto-merged by Dependabot workflow',
              merge_method: 'squash'
            });

      - name: Comment on major updates
        if: fromJSON(steps.check-update-type.outputs.result).isMajorUpdate
        uses: actions/github-script@v7
        with:
          script: |
            const { pull_request } = context.payload;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pull_request.number,
              body: `⚠️ **Major Version Update Detected**
              
              This PR contains a major version update that requires manual review.
              
              Please:
              1. Review the changelog for breaking changes
              2. Test the application thoroughly
              3. Update any affected code
              4. Manually merge when ready
              
              The automated tests have passed, but manual verification is recommended for major updates.`
            });